"""empty message

Revision ID: 294e67bf845c
Revises: 6c5da30f62cc
Create Date: 2020-09-02 20:07:56.092840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '294e67bf845c'
down_revision = '6c5da30f62cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('link', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'link')
    # ### end Alembic commands ###
