"""empty message

Revision ID: 4906c9779fdc
Revises: ef8cd858981e
Create Date: 2020-08-23 01:46:10.154183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4906c9779fdc'
down_revision = 'ef8cd858981e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('text', sa.String(length=300), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'text')
    # ### end Alembic commands ###
