"""empty message

Revision ID: 503be6093015
Revises: 8ba1ac17a7de
Create Date: 2020-06-20 23:56:28.525910

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '503be6093015'
down_revision = '8ba1ac17a7de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###
