"""empty message

Revision ID: 6ef3a136cf4c
Revises: dc8b0110ce70
Create Date: 2020-06-13 00:09:13.539025

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ef3a136cf4c'
down_revision = 'dc8b0110ce70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'users', ['username'])
    op.drop_column('users', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('name', sa.VARCHAR(length=50), nullable=True))
    op.drop_constraint(None, 'users', type_='unique')
    # ### end Alembic commands ###
