"""empty message

Revision ID: 8ba1ac17a7de
Revises: 1a93b74a1867
Create Date: 2020-06-20 23:54:33.290037

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba1ac17a7de'
down_revision = '1a93b74a1867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('text', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('description', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('posts', 'text')
    # ### end Alembic commands ###
