"""empty message

Revision ID: b8a2749d6bbd
Revises: 07e676341278
Create Date: 2020-06-21 00:01:42.791096

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b8a2749d6bbd'
down_revision = '07e676341278'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_column('posts', 'created_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('created_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
