"""empty message

Revision ID: cba98ef7b2f6
Revises: 4906c9779fdc
Create Date: 2020-08-23 10:50:46.544630

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cba98ef7b2f6'
down_revision = '4906c9779fdc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('parent_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'parent_id')
    # ### end Alembic commands ###
